// <auto-generated />
namespace PatelMilkProducts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class EmpAccountCreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmpAccountCreation));
        
        string IMigrationMetadata.Id
        {
            get { return "201912200450268_EmpAccountCreation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
